        {
          id: "m1-chapter-7-migrate-to-autonomous",
          title: "Chapter 7: Migrate to Autonomous",
          description: "Migration tools, methods, and best practices for Oracle Autonomous Database",
          questions: [
            { id: 1, question: "Which Oracle tool is best suited for migrating an on-premises Oracle database to Oracle Autonomous Database with near-zero downtime?", options: [{ id: "A", text: "Oracle Zero Downtime Migration (ZDM)" }, { id: "B", text: "SQL*Loader" }, { id: "C", text: "Oracle Data Pump" }, { id: "D", text: "Oracle Cloud Infrastructure Object Storage" }], correctAnswer: "A", explanation: "ZDM automates the migration workflow by combining logical migration tools and replication technologies to minimize business interruption." },
            { id: 2, question: "When performing a standard offline logical migration to Oracle Autonomous Database, which tool is primarily recommended to export and import schemas and data?", options: [{ id: "A", text: "DBMS_CLOUD" }, { id: "B", text: "Oracle GoldenGate" }, { id: "C", text: "Oracle Data Pump" }, { id: "D", text: "Oracle Recovery Manager (RMAN)" }], correctAnswer: "C", explanation: "Data Pump is the standard highly optimized Oracle utility for logical migration of schemas and data to Autonomous Database." },
            { id: 3, question: "What is the recommended staging area for transferring Oracle Data Pump dump files before importing them into an Oracle Autonomous Database?", options: [{ id: "A", text: "On-premises local storage" }, { id: "B", text: "OCI Block Volume" }, { id: "C", text: "OCI Object Storage" }, { id: "D", text: "OCI File Storage" }], correctAnswer: "C", explanation: "Data Pump dump files are typically uploaded to OCI Object Storage which Autonomous Database can directly and securely access for the import process." },
            { id: 4, question: "Which Oracle Cloud Infrastructure (OCI) fully managed service leverages the Zero Downtime Migration (ZDM) engine to provide enterprise-level database migration?", options: [{ id: "A", text: "OCI Data Integration" }, { id: "B", text: "Oracle Data Safe" }, { id: "C", text: "OCI Database Migration Service" }, { id: "D", text: "OCI GoldenGate" }], correctAnswer: "C", explanation: "This service provides a fully managed, intuitive cloud interface for enterprise migrations, powered seamlessly by the underlying ZDM engine." },
            { id: 5, question: "Which underlying technologies does Oracle Zero Downtime Migration (ZDM) utilize to achieve an online migration to Autonomous Database?", options: [{ id: "A", text: "SQL*Loader and DBMS_CLOUD" }, { id: "B", text: "Oracle Data Pump and Oracle GoldenGate" }, { id: "C", text: "Storage Gateways and FastConnect" }, { id: "D", text: "RMAN and Data Guard" }], correctAnswer: "B", explanation: "ZDM orchestrates Data Pump for the initial logical data instantiation and GoldenGate for real time synchronization to ensure zero downtime." },
            { id: 6, question: "Before migrating an on-premises database to Oracle Autonomous Database, which tool should be run to identify potential compatibility issues or unsupported features?", options: [{ id: "A", text: "Oracle SQL Developer Data Modeler" }, { id: "B", text: "Autonomous Health Framework (AHF)" }, { id: "C", text: "Cloud Premigration Advisor Tool (CPAT)" }, { id: "D", text: "Oracle Enterprise Manager" }], correctAnswer: "C", explanation: "CPAT is a script-based advisor that analyzes the source database schema and configuration, providing a readiness report and highlighting blockers." },
            { id: 7, question: "When using Oracle Data Pump to migrate to an Autonomous Database, which of the following is considered a best practice?", options: [{ id: "A", text: "Exclude database statistics during export" }, { id: "B", text: "Always use the SYS user with SYSDBA privileges" }, { id: "C", text: "Export directly using unencrypted standard network database links" }, { id: "D", text: "Perform a physical block-by-block copy of all datafiles" }], correctAnswer: "A", explanation: "Excluding statistics reduces export and import times, and Autonomous Database will automatically gather optimal statistics for its own environment post-import." }
          ]
        }
