        {
          id: "m1-chapter-5-autonomous-db-tools",
          title: "Chapter 5: Autonomous Database Tools",
          description: "Use Autonomous Database with Oracle APEX and Machine Learning",
          questions: [
            { id: 1, question: "Fine-Grained Data Visibility Scenario: A healthcare organization is building a patient portal using Oracle APEX. Medical receptionists need to see patient names and appointment times, but strict privacy regulations dictate that only assigned doctors can view the specific diagnostic codes and treatment history columns. Which feature allows developers to enforce this exact level of visibility?", options: [{ id: "A", text: "Identity Integration" }, { id: "B", text: "Access control" }, { id: "C", text: "Universal Theme" }, { id: "D", text: "App Builder" }], correctAnswer: "B", explanation: "Access control allows developers to define exactly who can see and do what, providing fine-grained control over users, roles, and data access down to the row and column level." },
            { id: 2, question: "Corporate Authentication Scenario: A large enterprise is deploying a new internal APEX application. IT policy requires that employees log into the new app using the company's existing corporate credentials via a central Single Sign-On (SSO) provider, avoiding the need to create new usernames and passwords. Which foundational capability makes this straightforward to implement?", options: [{ id: "A", text: "Data Isolation" }, { id: "B", text: "Workflow" }, { id: "C", text: "Identity Integration" }, { id: "D", text: "Compliance" }], correctAnswer: "C", explanation: "Identity Integration allows applications to easily federate with popular identity providers (IdPs) to enable single sign-on and centralized identity management without complex configuration." },
            { id: 3, question: "Concurrent Business Processes Scenario: A financial services company is modernizing its loan approval system. The new architecture requires that once an application is submitted, background checks and credit score evaluations must trigger and run simultaneously rather than waiting for one to finish before the other starts. Which platform enhancement should the development team leverage?", options: [{ id: "A", text: "Components" }, { id: "B", text: "Workflow" }, { id: "C", text: "Auditing" }, { id: "D", text: "Translations" }], correctAnswer: "B", explanation: "Enhanced workflow capabilities include support for parallel flows, allowing multiple complex steps to execute concurrently, along with new APIs for greater extensibility." },
            { id: 4, question: "Secure External Integrations Scenario: A software engineer needs to connect their APEX application to a highly secure external banking API. This connection requires dynamic OAuth scopes and signed assertions to authenticate properly before fetching financial data. Which platform enhancement area provides the specific support needed for this connection?", options: [{ id: "A", text: "Security" }, { id: "B", text: "Universal Theme" }, { id: "C", text: "Data Isolation" }, { id: "D", text: "App Builder" }], correctAnswer: "A", explanation: "Recent security enhancements strengthen how applications connect and operate by providing REST data source support for dynamic OAuth scopes, signed assertions, and password flows." },
            { id: 5, question: "Global Application Localization Scenario: A retail company is launching its internal inventory application in three new countries. The development team needs to localize the application into Spanish, French, and German efficiently, but they want to avoid the high maintenance overhead of creating and updating separate \"shadow\" applications for each language. Which enhancement provides a simplified solution for this requirement?", options: [{ id: "A", text: "Font APEX 2.5 updates" }, { id: "B", text: "Workspace-level SMTP controls" }, { id: "C", text: "Builder Extension backlinks" }, { id: "D", text: "Message-based translation model" }], correctAnswer: "D", explanation: "A new message-based translation model simplifies how applications are localized, making it easier to manage and update translations without needing to maintain separate shadow applications." },
            { id: 6, question: "What does AutoML primarily automate in the context of Oracle Machine Learning?", options: [{ id: "A", text: "Data visualization tasks" }, { id: "B", text: "The workflow for in-database machine learning classification and regression algorithms" }, { id: "C", text: "Database backup and recovery" }, { id: "D", text: "Cloud storage provisioning" }], correctAnswer: "B", explanation: "AutoML automates the complete machine learning workflow inside Oracle Database, including algorithm selection, feature selection, and model tuning for classification and regression models." },
            { id: 7, question: "Which two interfaces can be used to access AutoML in Oracle Autonomous Database?", options: [{ id: "A", text: "OML4Py and OML AutoML UI" }, { id: "B", text: "OML4R and SQL Developer" }, { id: "C", text: "APEX and REST API only" }, { id: "D", text: "OML4Py and OML4SQL only" }], correctAnswer: "A", explanation: "Oracle provides two official AutoML interfaces: OML4Py (Python API) and OML AutoML UI (No-code graphical interface)" },
            { id: 8, question: "How many steps make up the OML AutoML UI pipeline?", options: [{ id: "A", text: "Three" }, { id: "B", text: "Four" }, { id: "C", text: "Five" }, { id: "D", text: "Six" }], correctAnswer: "C", explanation: "The AutoML UI pipeline has five stages: 1. Adaptive Sampling 2. Algorithm Selection 3. Feature Selection 4. Model Tuning 5. Feature Selection Impact" },
            { id: 9, question: "What is the overarching goal of algorithm selection in AutoML?", options: [{ id: "A", text: "To reduce the number of hyperparameters" }, { id: "B", text: "To choose an algorithm that provides a model with the highest predictive accuracy" }, { id: "C", text: "To eliminate redundant data rows" }, { id: "D", text: "To increase the dataset size" }], correctAnswer: "B", explanation: "Algorithm selection uses meta learning to predict which algorithm is most likely to produce the most accurate model without trying every available algorithm." },
            { id: 10, question: "Scenario-Based Question A data scientist is working with a dataset containing 500 columns. Many columns are highly correlated or provide no predictive value. She wants AutoML to automatically remove these unnecessary columns before building the model.", options: [{ id: "A", text: "Automated algorithm selection" }, { id: "B", text: "Automated feature selection" }, { id: "C", text: "Automated model tuning" }, { id: "D", text: "Adaptive sampling" }], correctAnswer: "B", explanation: "Feature selection identifies and removes irrelevant or redundant columns, reducing noise and improving model efficiency. It works on features (columns) rather than rows or algorithms." },
            { id: 11, question: "Scenario-Based Question A team building an in-database classification model wants AutoML to avoid testing every available algorithm because doing so would consume too much time and computing resources. Instead, they want AutoML to intelligently predict which algorithms are most likely to perform well.", options: [{ id: "A", text: "Automated feature selection" }, { id: "B", text: "Automated model tuning" }, { id: "C", text: "Automated algorithm selection" }, { id: "D", text: "Adaptive sampling" }], correctAnswer: "C", explanation: "Algorithm selection uses meta learning to analyze dataset characteristics and predict which algorithms are likely to perform best. This avoids exhaustive testing and significantly reduces computation time." },
            { id: 12, question: "How many main steps does OML4Py's AutoML process consist of?", options: [{ id: "A", text: "Two" }, { id: "B", text: "Three" }, { id: "C", text: "Four" }, { id: "D", text: "Five" }], correctAnswer: "B", explanation: "OML4Py AutoML has three major steps: 1. Automated Algorithm Selection 2. Automated Feature Selection 3. Automated Model Tuning" },
            { id: 13, question: "What is the primary aim of adaptive sampling in the OML AutoML UI pipeline?", options: [{ id: "A", text: "To eliminate noisy features from the dataset" }, { id: "B", text: "To find the smallest sample size that adequately represents the full dataset" }, { id: "C", text: "To rank algorithms based on predicted performance" }, { id: "D", text: "To tune hyperparameters using gradient descent" }], correctAnswer: "B", explanation: "Adaptive sampling selects the smallest representative sample of the data. This reduces computation time while maintaining model accuracy." },
            { id: 14, question: "What is the primary aim of feature selection?", options: [{ id: "A", text: "To choose features in the dataset that are most predictive of the target, reducing dataset size" }, { id: "B", text: "To increase the number of algorithms tested" }, { id: "C", text: "To determine the sample size" }, { id: "D", text: "To rank algorithms by performance" }], correctAnswer: "A", explanation: "Feature selection removes unnecessary or irrelevant columns, keeping only the features that contribute to prediction. This improves efficiency and often increases model quality." },
            { id: 15, question: "What is the purpose of model tuning in the AutoML pipeline?", options: [{ id: "A", text: "To determine the set of hyperparameter values that produce a higher quality model" }, { id: "B", text: "To reduce the number of algorithms considered" }, { id: "C", text: "To select the smallest representative sample" }, { id: "D", text: "To rank features by predictive impact" }], correctAnswer: "A", explanation: "Model tuning automatically searches for the best hyperparameter values to improve the model's predictive performance." }
          ]
        }